### ISSUE TITLE
上傳檔案位置Scripts問題！

### ISSUE THREAD

**Issue by fiftycentsjj** [JackKuo-tw/PyDrive_backup#1]
您好：1.請問欲上傳的檔案，其資料夾在file_list裡面的路徑是/aaa/bbb/ccc.cc這樣嗎？
           2.如果欲上傳的是整個資料夾，如/aaa/bbb/，則其資料夾在file_list裡面的路徑是/aaa/bbb/這樣嗎？在file1.SetContentFile('/aaa/bbb/')也是這樣command的嗎？
　　　3.可以不要CreatFile嗎？只單純將資料夾或檔案上傳嗎？這樣scripts該如何寫呢？
不好意思，問題有點多，請您見諒。並煩請您不吝協助，謝謝您！

**Comment by JackKuo-tw** [comment]
1. 是的，在 README 格式範例中那樣，那三行分別代表 home 目錄底下所有檔案、html 目錄底下以 .html 結尾的所有檔案、還有 system.log 這個檔案
2. 上傳資料夾我沒試過呢，剛才找到[這份範例程式碼](https://github.com/gsuitedevs/PyDrive/blob/master/examples/using_folders.py)您可以參考看看
3. 這個 Python Package 已經有段時間沒有更新了，建議你可以直接去讀 Google Drive Api 尋求解答

P.S. 因爲每次要下載資料夾總是要等 Google 先對資料夾進行壓縮，這對網速快的用戶反而更浪費時間，因此我大多數時候都會壓縮，當然想要即時瀏覽就沒辦法了，希望有幫助到您！

**Comment by fiftycentsjj** [comment]
好的，真是謝謝您詳細的回覆。
